<a href="https://colab.research.google.com/github/aniketkanade25-dev/Ds_practical/blob/main/Practical3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

a. Create a 3x3 square matrix and compute its determinant.

In [5]:
import numpy as np

# Create a 3x3 matrix
matrix = np.array([
    [1, 2, 3],
    [5, 6, 4],
    [1, 3, 2]
])

print("Original 3x3 Matrix:")
print(matrix)

# Compute the determinant
determinant = np.linalg.det(matrix)

print(f"\nDeterminant of the matrix: {determinant}")


Original 3x3 Matrix:
[[1 2 3]
 [5 6 4]
 [1 3 2]]

Determinant of the matrix: 14.999999999999993


In [6]:
matrix = [
    [1, 2, 1],
    [4, 5, 6],
    [3, 5, 2]
]

print("The 3x3 matrix is:")
for row in matrix:
    print(row)

a = matrix[0][0]
b = matrix[0][1]
c = matrix[0][2]
d = matrix[1][0]
e = matrix[1][1]
f = matrix[1][2]
g = matrix[2][0]
h = matrix[2][1]
i = matrix[2][2]

determinant = a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)

print(f"\nThe determinant of the matrix is: {determinant}")

The 3x3 matrix is:
[1, 2, 1]
[4, 5, 6]
[3, 5, 2]

The determinant of the matrix is: 5


b. Find the inverse of the matrix

In [3]:
import numpy as np

# Input 3x3 matrix
A = np.array([
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0]
])

det = np.linalg.det(A)

if det == 0:
    print("Matrix is not invertible (determinant is 0).")
else:
    A_inv = np.linalg.inv(A)
    print("Inverse of the matrix:")
    print(A_inv)

Inverse of the matrix:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [4]:
def inverse_3x3(m):
    a, b, c = m[0]
    d, e, f = m[1]
    g, h, i = m[2]

    det = (a*(e*i - f*h)
           - b*(d*i - f*g)
           + c*(d*h - e*g))

    if det == 0:
        return None

    inv = [
        [(e*i - f*h)/det, (c*h - b*i)/det, (b*f - c*e)/det],
        [(f*g - d*i)/det, (a*i - c*g)/det, (c*d - a*f)/det],
        [(d*h - e*g)/det, (b*g - a*h)/det, (a*e - b*d)/det]]

    return inv

matrix = [
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0]]

result = inverse_3x3(matrix)

if result is None:
    print("Matrix is not invertible.")
else:
    print("Inverse matrix:")
    for row in result:
        print(row)

Inverse matrix:
[-24.0, 18.0, 5.0]
[20.0, -15.0, -4.0]
[-5.0, 4.0, 1.0]


c) Solve the following system of linear equations using NumPy: 2x+3y=10, 4x+5y=20

In [1]:
import numpy as np

# Coefficient matrix
A = np.array([
    [2, 3],
    [4, 5]
])

# Constants
B = np.array([10, 20])

# Solve Ax = B
solution = np.linalg.solve(A, B)

x = solution[0]
y = solution[1]

print("x =", x)
print("y =", y)


x = 5.0
y = 0.0


In [2]:
# Coefficients
a1, b1, c1 = 2, 3, 10
a2, b2, c2 = 4, 5, 20

# Make the x coefficients the same
m1 = a2
m2 = a1

# Multiply equations to match x terms
A1 = a1 * m1
B1 = b1 * m1
C1 = c1 * m1

A2 = a2 * m2
B2 = b2 * m2
C2 = c2 * m2

# Subtract equations to eliminate x
y = (C1 - C2) / (B1 - B2)

# Substitute y back to find x
x = (c1 - b1 * y) / a1

print("x =", x)
print("y =", y)

x = 5.0
y = 0.0
